chore(v3): final checks and reconciliation before release
Scaffold-Stark/scaffold-stark-2 pull request #274
Opened 2024-09-06 15:12 UTC by metalboyrick

# Task name here

Fixes #262 

## Types of change

- [ ] Feature
- [ ] Bug
- [X] Enhancement

## Comments (optional)

2024-09-06 16:04 UTC, metalboyrick commented
putting it up for visibility for now @0xquantum3labs

2024-09-07 18:49 UTC, Nadai2010 requested changes
Great job @metalboyrick, when I can I'll check out some comments

2024-09-07 18:49 UTC, Nadai2010 commented on packages/snfoundry/contracts/src/test/TestContract.cairo
Here the test is not the same as the [main](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/snfoundry/contracts/src/test/TestContract.cairo) one, the `fn OWNER()` is missing, was it changed for some reason?

2024-09-07 18:49 UTC, Nadai2010 commented on packages/nextjs/app/debug/_components/contract/utilsContract.tsx
Here I see differences with the main [utilsContract.tsx](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/nextjs/app/debug/_components/contract/utilsContract.tsx#L20) one, especially related to const `isJsonString`. Was it removed for any specific reason?

2024-09-07 18:49 UTC, Nadai2010 commented on packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
Here I see differences with the [main](https://github.com/Scaffold-Stark/scaffold-stark-2/blob/main/packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx) one, although I think everything is correct and has been optimized, also better defined names, I leave it just as a note to have it under control and check.

2024-09-08 03:15 UTC, metalboyrick commented on packages/snfoundry/scripts-ts/deploy-contract.ts
noted will help to add these stuff in

2024-09-08 03:16 UTC, metalboyrick commented on packages/snfoundry/contracts/src/test/TestContract.cairo
hmm im not sure as i was just merging the main into this v3 branch, if this function is needed then can put it back, cc @jrcarlos2000 @0xquantum3labs

2024-09-08 03:18 UTC, metalboyrick commented on packages/nextjs/app/debug/_components/contract/utilsContract.tsx
not removed, it was moved to another file, since I thought it was more generic and I needed it for another function in a different file.

2024-09-08 03:18 UTC, metalboyrick commented on packages/nextjs/app/debug/_components/contract/utilsContract.tsx
v3 parsing is a bit different than v2 since the newer hooks from `starknet-react` work a bit differently

2024-09-08 03:19 UTC, metalboyrick commented on packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
yep, do expect some differences with the main branch which is the current v2 version

2024-09-08 06:57 UTC, Nadai2010 approved these changes

2024-09-08 10:37 UTC, 0xquantum3labs requested changes
please update the cairo version on `scarb.toml` and the corresponding dependencies, as well as `README.md`

2024-09-08 16:14 UTC, metalboyrick commented
docs update PR: https://github.com/Scaffold-Stark/ss2-docs/pull/17

2024-09-08 16:29 UTC, merged