test: create test for useScaffoldWriteContract hook
Scaffold-Stark/scaffold-stark-2 pull request #316
Opened 2024-10-05 17:55 UTC by NueloSE

#291 

Add test

## Types of change

- [x] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

![Screenshot from 2024-10-05 17-00-08](https://github.com/user-attachments/assets/92406697-87ae-4c21-acd1-90839edc2979)

2024-10-06 11:18 UTC, metalboyrick requested changes
Thanks for the hard work ! Left some syntactic comments!

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> +    console.log(mockSendTransaction.sendAsync.mock.calls[0]);
please remove any logs when not needed, this will clutter the test CLI

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> +    expect(useDeployedContractInfo).toHaveBeenCalledWith(contractName);
Redundant check, line 144 is not needed if you have 145.

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> +    expect(mockSendTransaction.sendAsync).toHaveBeenCalledWith([
Redundant check, Line 124 is not needed when you have 126

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> +
Please add a mock cleanup with `afterAll`

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> +    expect(useDeployedContractInfo).toHaveBeenCalledWith(contractName);
Please check your code whether you have similar cases and fix that as well

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldMultiWriteContract.test.ts
> +    (useTransactor as Mock).mockReturnValue(mockTransactor);
For this and other similar cases, you can define the mock before the top `describe` block, here is the example:

```ts
const useTransactorMock = useTransactor as Mock;

describe("useScaffoldWriteContract", () => {
  // ...test suites
})
```

The reason is that we want to clearly distinguish mock and real ones, also when doing tests, we don't have to repeatedly do type assertions.

Kindly check for other similar case and make changes as well.

2024-10-06 11:18 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldMultiWriteContract.test.ts
> +  const mockedUseNetwork = useNetwork as unknown as Mock;
You don't need `unknown` here, and you can move this to outside the `describe` block

2024-10-06 22:34 UTC, Nadai2010 commented
Hi @NueloSE please review the changes requested by @metalboyrick ODHack is about to end

2024-10-07 01:48 UTC, NueloSE commented
@Nadai2010 @metalboyrick sorry for the late fix. Issues with power. Hope implemented changes didn't come too late

2024-10-07 02:42 UTC, metalboyrick approved these changes
No worries, awesome stuff! Looks good to me

2024-10-07 02:42 UTC, metalboyrick commented
@NueloSE just make sure the tests still run good!

2024-10-07 12:01 UTC, merged