Add yarn deploy --noreset and modify yarn deploy
Scaffold-Stark/scaffold-stark-2 pull request #321
Opened 2024-10-11 12:32 UTC by Nadai2010

# Add yarn deploy --noreset and modify yarn deploy

- Integrated and modified `yarn deploy` now always resets contracts.
- Integration of `yarn deploy --noreset`, this new command does not reset previous deployments.

Fixes #285 

## Types of change

- [x] Feature
- [x] Bug
- [x] Enhancement

2024-10-12 10:03 UTC, Johnnysoltani approved these changes

2024-10-12 10:11 UTC, Johnnysoltani approved these changes

2024-10-12 10:11 UTC, Johnnysoltani approved these changes

2024-10-12 11:32 UTC, 0xquantum3labs requested changes

2024-10-12 11:32 UTC, 0xquantum3labs commented on package.json
> +    "deploy:noreset": "yarn workspace @ss-2/snfoundry deploy --noreset",
lets use `--no-reset`

2024-10-12 15:22 UTC, metalboyrick commented on package.json
> +    "deploy:noreset": "yarn workspace @ss-2/snfoundry deploy --noreset",
@Nadai2010 also `deploy:no-reset`

2024-10-14 14:15 UTC, metalboyrick commented
Note that i used reverse of `reset` instead of hardcoding a `no-reset` parameter, this is due to yargs ability to directly parse `--no-reset` into `reset = false`.

2024-10-14 15:01 UTC, 0xquantum3labs approved these changes

2024-10-14 15:01 UTC, merged