Sync Coingecko Api from scaffold-eth-stark
Scaffold-Stark/scaffold-stark-2 pull request #354
Opened 2024-11-15 03:15 UTC by Buuh2511

# Sync Coingecko Api from scaffold-eth-stark

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

## Comments (optional)
- Coingecko api sync created by Iossocket in eth-stark repo

2024-11-15 03:31 UTC, iossocket commented
Hi @Buuh2511 , would you mind to check this pull request https://github.com/Scaffold-Stark/scaffold-stark-2/pull/353, it changed the price api trigger and cache behaviour, also move the api call to server side

2024-11-15 04:18 UTC, Buuh2511 commented
yes sir @iossocket, i will check PR #353

2024-11-15 04:26 UTC, Nadai2010 requested changes

2024-11-15 04:26 UTC, Nadai2010 commented on packages/nextjs/contracts/deployedContracts.ts
This file is auto-generated, we will not upload these changes

2024-11-15 04:29 UTC, Buuh2511 commented on packages/nextjs/contracts/deployedContracts.ts
yes sir

2024-11-15 04:54 UTC, Nadai2010 commented on packages/nextjs/contracts/deployedContracts.ts
I think everything in this PR has been fixed in #353 by @iossocket , apart from the deployedContract.ts it should always be uploaded empty.

what is the difference vs PR353?

2024-11-15 04:59 UTC, Buuh2511 commented on packages/nextjs/contracts/deployedContracts.ts
u are right sir, i just do a sync from scaffold-eth-stark repo to scaffold-stark-2 for api coingecko feature. then i think we can move on PR #353 and close this PR

2024-11-15 05:10 UTC, Nadai2010 commented on packages/nextjs/contracts/deployedContracts.ts
Perfect sir, we see that the CORS errors are also resolved, let's wait for the 353 to be merged and close this PR, and sync with scaffold-eth-stark

2024-11-18 10:01 UTC, Nadai2010 commented on packages/nextjs/contracts/deployedContracts.ts
Hi @Buuh2511, I think we can close this PR

2024-11-18 10:07 UTC, Buuh2511 commented on packages/nextjs/contracts/deployedContracts.ts
yes sir, im going to close this PR

2024-11-18 10:07 UTC, closed without merging