Added a placeholder if wallet not connected
Scaffold-Stark/scaffold-stark-2 pull request #385
Opened 2024-12-13 16:37 UTC by melnikga

# [FEAT] Add a placeholder if wallet not connected #368

Fixes #relevant-issue-here

## Types of change

- [ ] The text "You haven't connected your wallet yet" has been added to the skeleton component, and the logic of displaying the skeleton has also been changed

## Comments (optional)

2024-12-13 16:41 UTC, melnikga commented
The mobile version is not ready yet, I will finish it in the next commit soon

2024-12-13 16:43 UTC, melnikga commented
Let me know if you are satisfied with this solution to the problem. In that case, I'll finish the mobile version and we can  merge

2024-12-14 06:27 UTC, Nadai2010 commented
Hi @melnikga, please check that all CI tests are green, `yarn format:check` should correct the correct format.

We will check the placeholder changes and let you know.

2024-12-14 06:47 UTC, Nadai2010 requested changes
I believe the idea is to avoid having it stuck in a loading state, acting as if it’s "loading."  

We just need it to display something short, like "Wallet not connected" or simila

- No gray background and definitely no "Connect" button.

![Captura desde 2024-12-14 06-41-36](https://github.com/user-attachments/assets/2cf5821b-db07-465e-8ee8-2946154108ea)

2024-12-14 14:19 UTC, metalboyrick approved these changes
looks good to me

2024-12-14 19:37 UTC, Nadai2010 approved these changes

2024-12-14 19:38 UTC, merged

2024-12-14 19:38 UTC, Nadai2010 commented
Thanks @melnikga e now I like it, the mobile version also adapts to the design.