write test for utils/scaffold-stark/common.ts
Scaffold-Stark/scaffold-stark-2 pull request #387
Opened 2024-12-13 20:57 UTC by Benjtalkshow

## [TEST] Create unit tests for `utils/scaffold-stark/common.ts` file 

Fixes #372 

## Types of change
- [x] Enhancement

## Test covers
- [x] Conversion of BigInt values to strings.
- [x] Handling of non-BigInt values (returning them as-is).
- [x] Validation of correct Ethereum addresses `(40 hexadecimal characters with '0x' prefix)`.
- [x] Rejection of invalid addresses (wrong length, missing prefix, invalid characters). 
- [x] Conversion of non-zero BigInt values to hexadecimal strings.
- [x] Handling of zero as a BigInt. 
- [x] Validation of correct JSON strings (objects, arrays, and simple values).
- [x] Rejection of invalid JSON strings (malformed JSON, non-JSON strings, empty strings). 
- Test
![image](https://github.com/user-attachments/assets/3703eddb-f00f-4f62-9cf5-5075bd9b412b)
- Test coverage
![image](https://github.com/user-attachments/assets/fecd51fd-4360-47b7-b943-3279c3e8973e)

2024-12-13 20:57 UTC, Benjtalkshow commented
@metalboyrick 
Please review.

2024-12-14 06:25 UTC, Nadai2010 commented
Hi @Benjtalkshow , please check that all CI tests are green, `yarn format:check` should correct the correct format.

2024-12-14 14:32 UTC, metalboyrick requested changes
Please make sure CI is green.

2024-12-14 17:44 UTC, Benjtalkshow commented
> Please make sure CI is green.

@Nadai2010 
@metalboyrick 
Done

2024-12-14 19:39 UTC, Nadai2010 approved these changes

2024-12-14 19:41 UTC, Nadai2010 commented
For me everything is correct @Benjtalkshow, thanks for the work, we look forward to the 2nd review @metalboyrick and to make the merge or the changes they request.

2024-12-15 00:34 UTC, metalboyrick approved these changes

2024-12-15 00:35 UTC, merged