fix: useScaffoldContract write bug with external wallets #252
Scaffold-Stark/scaffold-stark-2 pull request #390
Opened 2024-12-14 15:01 UTC by ShantelPeters

# Task name here

Fixes #relevant-issue-here

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

2024-12-14 19:55 UTC, Nadai2010 commented
Hi @ShantelPeters , run the `yarn format` command to correct the format with the correct rules and check that the github CI is green.

2024-12-16 08:55 UTC, ShantelPeters commented
Hi, ran
`$ yarn format`
and
```
$ yarn format:check
Checking formatting...
All matched files use Prettier code style!
Checking formatting...
All matched files use Prettier code style!
```
and found no problems.

2024-12-16 14:15 UTC, iossocket commented on packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts
> +  }, [deployedContractData, publicClient]);
please add unit tests to cover the logic inside of `useMemo`, thanks

2024-12-17 05:52 UTC, ShantelPeters commented
![Screenshot from 2024-12-17 06-39-14](https://github.com/user-attachments/assets/f72e5740-284f-41e1-8bce-145088e3bb00)

2024-12-17 09:31 UTC, metalboyrick requested changes
I think this PR has not address the issue correctly ser. The intention is to make the contract instance be able to write.

i tried testing it with the following implementation:

<img width="943" alt="image" src="https://github.com/user-attachments/assets/d1edaa21-469e-4dd9-9074-fc425e8c3266" />

and got this error:

![image](https://github.com/user-attachments/assets/3d2c730e-29c7-42b3-b5e5-2a3c65b37299)

I noticed that you have not included wallet client when creating the instance. Public Client cannot do any write signature since they don't sign anything.

2024-12-17 09:31 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts
> +      publicClient
should involve `WalletClient` or `Account` instance since `publicClient` cannot sign messages.

2024-12-18 02:43 UTC, metalboyrick requested changes
please also make sure that writing with the hooks work, the most important thing is it woks.

2024-12-18 02:43 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts
> +      account,
use `publicClient` as fallback value

2024-12-19 00:00 UTC, metalboyrick requested changes
GM Ser, unfortunately the issue from before still persists.

Also, I tried using another implementation and got the following error

Implementation: 
<img width="854" alt="image" src="https://github.com/user-attachments/assets/94c09271-16d2-4320-ae6e-5e017f40918f" />


Error:
<img width="815" alt="image" src="https://github.com/user-attachments/assets/1fe57165-4f0a-4fd9-9075-8241448eab72" />

I think it would be helpful to refer to the previous issue on this matter: #243

2024-12-21 03:59 UTC, metalboyrick requested changes
minor comments left, nice work on fixing the write issue! works on my end. 

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/2bd6b742-72c3-4712-ba34-993c87431bd2" />

2024-12-21 03:59 UTC, metalboyrick commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts
> +  // });
lets clean up the comments

2024-12-21 05:24 UTC, ShantelPeters commented on packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts
> +  // });
Fixed, ser.

2024-12-21 09:17 UTC, metalboyrick approved these changes

2024-12-21 09:17 UTC, merged