tests: unit tests for utils/scaffold-stark/contract.ts #373
Scaffold-Stark/scaffold-stark-2 pull request #391
Opened 2024-12-14 15:27 UTC by od-hunter

# Task name here

Fixes #relevant-issue-here

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

## Comments (optional)

2024-12-14 19:35 UTC, Nadai2010 requested changes
Hi, thank you for your work on this!

- Please ensure you run `yarn format` to align the code with the formatting rules.
- The test path should be corrected to `utils/scaffold-start/__test__/contract.test.ts`. Make sure to include the `__test__` folder in the path.
- I'm encountering some error warnings related to the ABI (see the attached image for reference):  
  ![ABI Error Warnings](https://github.com/user-attachments/assets/e573db7c-18a2-4b04-bc68-be4fa91bba9d)
- Additionally, the test coverage is not at 100% (see the attached coverage report):  
  ![Coverage Report](https://github.com/user-attachments/assets/84cef2a1-d04b-4e81-9727-8d668e8bb41e)

2024-12-15 08:28 UTC, metalboyrick requested changes
please address @Nadai2010 comments as well, they are important. 

On coverages cc @Nadai2010, not reaching 100% is fine but should be at least at 80%, currently i see 60%-ish coverage only. kindly add more case or test more possible branching (`if` statements, `switch` statements, optional chaining, etc) to increase this number.

Thanks for the hard work!

2024-12-15 08:28 UTC, metalboyrick commented on packages/nextjs/utils/tests/contract.test.ts
> +  });
not sure what is this case for

2024-12-15 08:29 UTC, metalboyrick commented
Please attach a screenshot of the coverages as well @od-hunter

2024-12-16 11:08 UTC, od-hunter commented
Tests passing
![Screenshot from 2024-12-16 12-03-19](https://github.com/user-attachments/assets/e0cf88b0-4409-4bf5-9f5a-2050ad028afa)
, though error warnings proving otherwise.

2024-12-16 12:15 UTC, od-hunter commented
> Tests passing ![Screenshot from 2024-12-16 12-03-19](https://private-user-images.githubusercontent.com/146340502/396070942-e0cf88b0-4409-4bf5-9f5a-2050ad028afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNTE1NzcsIm5iZiI6MTczNDM1MTI3NywicGF0aCI6Ii8xNDYzNDA1MDIvMzk2MDcwOTQyLWUwY2Y4OGIwLTQ0MDktNGJmNS05ZjVhLTIwNTBhZDAyOGFmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMjE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjRhMDc0OGZlNjJiZTM1OTM4YjcwNTNkMjY0MDVlNmQwOTkxMTRjN2Q2MjUwNDYzNDVjYzg3YmE2OGJlMGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vQX9hh3mG4a4Pi00CYDm8sgXfsnVKAw8fQfaxUSlRms) , though error warnings proving otherwise, resolving the type mismatch.

Error warnings fixed.

2024-12-17 09:46 UTC, od-hunter commented
![Screenshot from 2024-12-17 10-24-02](https://github.com/user-attachments/assets/c8b3e447-0649-460a-b38e-9f21bf4c4838)\
The logic not covered are either private or functions logic in private functions.
![Screenshot from 2024-12-17 10-27-02](https://github.com/user-attachments/assets/12aaaadb-7fab-4928-b6c1-f8fd1d8a4365)

2024-12-17 15:29 UTC, od-hunter commented
@metalboyrick

2024-12-18 02:47 UTC, metalboyrick requested changes
you got this man, all the best!

2024-12-18 02:47 UTC, metalboyrick commented on packages/nextjs/utils/__test__/contract.test.ts
you forgot to delete this haha

2024-12-18 02:50 UTC, metalboyrick requested changes

2024-12-18 02:50 UTC, metalboyrick commented on packages/nextjs/utils/__test__/contract.test.ts
> +});
I don't think you should mock the stuff here, if you need to mock the functions on a one off basis, you can use the spy functions of vitest (https://vitest.dev/guide/mocking#functions). 

You can either play with the input or use the spy on the above to produce different cases, if some functions are private, sometimes it implies that you need to treat the logic inside as if they are part of the function without mocking.

2024-12-18 15:59 UTC, od-hunter commented
@metalboyrick please review

2024-12-19 00:02 UTC, metalboyrick approved these changes
looks good to me ! let's have @Nadai2010 review again to see if his issues are resolved, thanks for the hard work man!

2024-12-19 08:22 UTC, Nadai2010 requested changes
For me it's all good, we just need to move to the correct route that we discussed here. (2 point)

https://github.com/Scaffold-Stark/scaffold-stark-2/pull/391#pullrequestreview-2504244568

![imagen](https://github.com/user-attachments/assets/a7ab8b2f-0f65-4b7a-89bf-406bd03ee19c)

2024-12-19 09:03 UTC, od-hunter commented
@Nadai2010 , please review

2024-12-19 11:15 UTC, Nadai2010 approved these changes
Thank you for your work

2024-12-19 11:16 UTC, merged