Create hook useDataTransaction
Scaffold-Stark/scaffold-stark-2 pull request #396
Opened 2024-12-17 13:48 UTC by cidkagenow

#330 

add useDataTransaction

## Types of change

- [ ] Feature
- [ ] Enhancement

2024-12-17 14:00 UTC, iossocket commented on packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
>    const blockExplorerAddressLink = useMemo(() => {
two empty lines for?

2024-12-17 14:02 UTC, iossocket commented on packages/nextjs/hooks/scaffold-stark/useDataTransaction.ts
> +export const useDataTransaction = (blockNumber: number) => {
pls add unit tests for this hook, thanks

2024-12-19 09:06 UTC, Nadai2010 requested changes
When testing I receive several isuue, please solve it.

![Captura desde 2024-12-19 08-39-06](https://github.com/user-attachments/assets/a3f8f4cc-3f4a-4610-b82d-048a7b4b83e4)

2024-12-19 09:23 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/useDataTransaction.ts
> +  blockVersion: string;
I I think it is better to call it starknetVersion here, as it is really the version that is returned.

2024-12-19 09:23 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/useDataTransaction.ts
> +  blockNewroot: string;
The blockNerRoot I think it is better to change it to parentBlockHash,

2024-12-19 09:23 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/useDataTransaction.ts
A quick test using the Hook in Sepolia shows a good comparison in the metrics. (We should review the conversations of some data, that is already part of our hook. IMO) @metalboyrick 

![imagen](https://github.com/user-attachments/assets/4c5d6a4c-2142-4aba-a73a-9ede6ecf5e1b)

![imagen](https://github.com/user-attachments/assets/949fbba8-408b-4495-be98-9ab461e02454)


In Mainnet Todo OK

![imagen](https://github.com/user-attachments/assets/00e0b8ab-71fa-4269-b076-b34dd977e220)

![imagen](https://github.com/user-attachments/assets/aed955eb-8682-4b92-bbfd-3afce605400f)

In Devnet OK

![imagen](https://github.com/user-attachments/assets/2abfa288-d8d7-4e11-968f-96c3595f10ed)

2024-12-20 03:25 UTC, metalboyrick commented
yep thanks @Nadai2010 @iossocket for the review, can resolve the comments ser @cidkagenow !

2024-12-21 04:00 UTC, metalboyrick commented on packages/nextjs/contracts/deployedContracts.ts
> +const deployedContracts = {
hey @cidkagenow seems like this hasnt been resolved yet

2024-12-21 19:17 UTC, Nadai2010 requested changes

2024-12-21 19:17 UTC, Nadai2010 commented on packages/nextjs/hooks/scaffold-stark/useDataTransaction.ts
> +            return 4000; // Valor por defecto en caso de error
Please remove or put the comment in English, the rest would be fine by me.

2024-12-22 07:17 UTC, metalboyrick approved these changes
looks good to me!

2024-12-22 07:20 UTC, Nadai2010 approved these changes

2024-12-22 07:34 UTC, merged