Fixed [BUG] u256> display for non-zero u256
Scaffold-Stark/scaffold-stark-2 pull request #404
Opened 2024-12-22 20:01 UTC by jedstroke

# [BUG] u256> display for non-zero u256

![WhatsApp Image 2024-12-22 at 8 55 12 PM](https://github.com/user-attachments/assets/a0df5364-345a-45c2-8274-75bbec2c7dd1)

Fixes #344 

## Types of change

- [ ] Feature
- [x] Bug
- [ ] Enhancement

## Comments (optional)

2024-12-22 20:02 UTC, jedstroke commented
@Nadai2010 @metalboyrick

2024-12-23 08:29 UTC, metalboyrick requested changes

2024-12-23 08:29 UTC, metalboyrick commented on packages/nextjs/components/scaffold-stark/Input/EtherInput.tsx
> +      name={name?.replace(">", "")}
can't fix it like this because this will break happy paths

2024-12-23 08:49 UTC, metalboyrick commented
GM @jedstroke  seems like we will not be able to finish the PR in due time. Therefore we would not be able to consider this PR as an ODHack 11 PR, but you can still work on it but the rewards will not be part of the ODHack11 reward. 

Really appreciate the attempt!

2024-12-24 07:21 UTC, closed without merging

2024-12-24 07:23 UTC, Nadai2010 commented
Hello @jedstroke thank you for your contribution, this PR needs a lot of changes that explain many files uploaded that should not be, we close the issue by this ODHack